# Overwriting defaults from dz60/rules.mk

# MCU = atmega32u4
# BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no

RGBLIGHT_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
